baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Informo specifications"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir = false

ignorefiles = [ ]

[params]
  editURL = "https://github.com/Informo/specs/edit/master/content/"
  description = "Informo specifications"
  author = "Informo core team and contributors"
  showVisitedLinks = false
  disableBreadcrumb = true
  disableNextPrev = true
  themeVariant = "informo"
  disableInlineCopyToClipBoard = true

[outputs]
home = [ "HTML", "RSS", "JSON"]
