baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Informo specs"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir = false

[params]
  editURL = "https://github.com/Informo/specs/"
  description = "Informo specs documentation"
  author = "Informo team"
  showVisitedLinks = true
  disableBreadcrumb = true
  disableNextPrev = true
  themeVariant = "green"

[outputs]
home = [ "HTML", "RSS", "JSON"]

